import { initializeApp } from 'firebase/app';
import { getFirestore, doc, getDoc, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDtW1Xrpf_jcDKd12IyB88AjiVDRe7e0SE",
  authDomain: "organiclog-2f6c7.firebaseapp.com",
  projectId: "organiclog-2f6c7",
  storageBucket: "organiclog-2f6c7.firebasestorage.app",
  messagingSenderId: "267681135810",
  appId: "1:267681135810:web:5e62b67eb2d4145a4b8f5b"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// ============================================================================
// 原材料マスタ (Ingredients)
// ============================================================================
const ingredients = [
  // --- 有機食材 (organic) ---
  { id: 'ing-org-ninjin',        name: '有機人参',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-nukadoko',      name: '有機ぬか床',         type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-korinky',       name: '有機コリンキー',     type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-piman',         name: '有機ピーマン',       type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-mint',          name: '有機ミント',         type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-shoyu',         name: '有機醤油',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-kurozu',        name: '有機黒酢',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-olive',         name: '有機オリーブオイル', type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-sugar',         name: '有機グラニュー糖',   type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-karashina',     name: '有機カラシナ',       type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-mizuna',        name: '有機水菜',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-nabana',        name: '有機菜花',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-hatsukadk',     name: '有機はつか大根',     type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-cauliflwr',     name: '有機カリフラワー',   type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-beets',         name: '有機ビーツ',         type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-kabu',          name: '有機カブ',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-tamanegi',      name: '有機たまねぎ',       type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-zucchini',      name: '有機ズッキーニ',     type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-tonyu',         name: '有機豆乳',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-italianp',      name: '有機イタリアンパセリ', type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-rosemary',      name: '有機ローズマリー',   type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-parsley',       name: '有機パセリ',         type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-yasai',         name: '有機野菜（ポタージュ用）', type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-kyuri',         name: '有機キュウリ',       type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-passion',       name: '有機パッションフルーツ', type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-tamanegi-s',    name: '有機玉ねぎ（ソース用）', type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-nasu',          name: '有機ナス',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-satoimo',       name: '有機里芋',           type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-jagaimo',       name: '有機ジャガイモ',     type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-coffee',        name: '有機コーヒー（トーホー）', type: 'organic', supplier: '過去データインポート' },
  { id: 'ing-org-shokuzensu',    name: '有機食前酢',         type: 'organic', supplier: '過去データインポート' },

  // --- 非有機食材 (general) ---
  { id: 'ing-gen-spice',         name: 'スパイス',           type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-blueberry',     name: 'ブルーベリー抽出物', type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-petitdrip',     name: 'プチドリップ',       type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-bpepper',       name: 'ブラックペッパー',   type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-sonota',        name: 'その他食材（非有機）', type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-salsa-hi',      name: 'サルサソース（非有機分）', type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-shokuzensu-hi', name: '食前酢（非有機分）', type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-dessert',       name: 'デザート（非有機）', type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-kobachi',       name: '小鉢（非有機）',     type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-main',          name: 'メイン（非有機）',   type: 'general', supplier: '過去データインポート' },
  { id: 'ing-gen-gohan',         name: 'ごはん（非有機）',   type: 'general', supplier: '過去データインポート' },
].map(ing => ({
  ...ing,
  hasCertificate: ing.type === 'organic',
  certificateExpiry: '',
  hasJasLabel: ing.type === 'organic',
  updatedAt: new Date().toISOString()
}));


// ============================================================================
// メニュー（レシピ）
// ============================================================================
const now = new Date().toISOString();

const menus = [
  // ---------- 1. 有機ぬか漬け ----------
  {
    id: 'menu-nukaduke-1',
    name: '有機ぬか漬け №1',
    masterName: '有機ぬか漬け',
    versionName: '第1版',
    isActiveVersion: false,
    price: 0,
    category: '料理',
    recipe: [
      { ingredientId: 'ing-org-ninjin', amount: 100 },
      { ingredientId: 'ing-org-nukadoko', amount: 200 },
    ],
    cookingInstructions: '1. 野菜に少々塩をふり手で全体にこする\n2. ぬか床に漬け込む、空気に触れないようにする\n3. 1日～2日で取り出し、完成。\n4. ぬか床を毎日かき混ぜる。',
    description: '有機野菜（人参）を有機ぬか床で漬け込んだ一品',
    managerApproved: '中村誠治',
    creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年2月20日',
    startDate: '令和6年3月1日',
    reviewDate: '令和7年2月20日',
    deadline: '一年間',
    courseTargetNum: '',
    singleTargetNum: '60食',
    changeDetails: '特になし',
    updatedAt: now,
  },
  {
    id: 'menu-nukaduke-2',
    name: '有機ぬか漬け №2',
    masterName: '有機ぬか漬け',
    versionName: '第2版（終了）',
    isActiveVersion: true,
    price: 0,
    category: '料理',
    recipe: [
      { ingredientId: 'ing-org-ninjin', amount: 100 },
      { ingredientId: 'ing-org-nukadoko', amount: 200 },
    ],
    cookingInstructions: '1. 野菜に少々塩をふり手で全体にこする\n2. ぬか床に漬け込む、空気に触れないようにする\n3. 1日～2日で取り出し、完成。\n4. ぬか床を毎日かき混ぜる。',
    description: '食数も少なく、手間もかかるため今回限りで終了とする',
    managerApproved: '中村誠治',
    creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年2月20日',
    startDate: '終了',
    reviewDate: '',
    deadline: '一年間',
    courseTargetNum: '',
    singleTargetNum: '60食',
    changeDetails: '食数少ない終了',
    remarks: '食数も少なく、手間もかかるため今回限りで終了とする',
    updatedAt: now,
  },

  // ---------- 2. オーガニックコース ----------
  {
    id: 'menu-orgcourse-1',
    name: 'オーガニックコース №1',
    masterName: 'オーガニックコース',
    versionName: '第1版',
    isActiveVersion: false,
    price: 0,
    category: '料理',
    recipe: [
      { ingredientId: 'ing-org-coffee', amount: 7 },
      { ingredientId: 'ing-org-shokuzensu', amount: 11 },
      { ingredientId: 'ing-org-olive', amount: 200 },     // 有機野菜のサルサソース
      { ingredientId: 'ing-org-tonyu', amount: 215 },      // 有機豆乳のポタージュ
      { ingredientId: 'ing-org-kurozu', amount: 30 },      // 有機野菜ピクルス
      { ingredientId: 'ing-org-ninjin', amount: 119 },     // 有機野菜サラダ
      { ingredientId: 'ing-org-tamanegi', amount: 40 },    // 有機野菜のバーニャカウダ
      { ingredientId: 'ing-gen-salsa-hi', amount: 5 },
      { ingredientId: 'ing-gen-shokuzensu-hi', amount: 0.5 },
      { ingredientId: 'ing-gen-dessert', amount: 70 },
      { ingredientId: 'ing-gen-kobachi', amount: 60 },
      { ingredientId: 'ing-gen-main', amount: 300 },
      { ingredientId: 'ing-gen-gohan', amount: 150 },
    ],
    cookingInstructions: '1. 各種有機料理はスペックで対応する。\n2. 小鉢・ごはん・デザートは、通常営業通り提供\n3. メイン料理はオーダー時作成\n4. セットを組み提供する',
    description: '有機料理をセットにしたオーガニックコース（有機52%、非有機48%）',
    managerApproved: '中村誠治',
    creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年8月25日',
    startDate: '令和6年9月1日',
    reviewDate: '令和7年8月25日',
    deadline: '一年間',
    courseTargetNum: '年間3600食',
    singleTargetNum: '',
    changeDetails: '特になし',
    updatedAt: now,
  },
  {
    id: 'menu-orgcourse-2',
    name: 'オーガニックコース №2',
    masterName: 'オーガニックコース',
    versionName: '第2版',
    isActiveVersion: true,
    price: 0,
    category: '料理',
    recipe: [
      { ingredientId: 'ing-org-coffee', amount: 7 },
      { ingredientId: 'ing-org-shokuzensu', amount: 11 },
      { ingredientId: 'ing-org-olive', amount: 200 },
      { ingredientId: 'ing-org-tonyu', amount: 215 },
      { ingredientId: 'ing-org-kurozu', amount: 30 },
      { ingredientId: 'ing-org-ninjin', amount: 119 },
      { ingredientId: 'ing-org-tamanegi', amount: 40 },
      { ingredientId: 'ing-gen-salsa-hi', amount: 5 },
      { ingredientId: 'ing-gen-shokuzensu-hi', amount: 0.5 },
      { ingredientId: 'ing-gen-dessert', amount: 70 },
      { ingredientId: 'ing-gen-kobachi', amount: 60 },
      { ingredientId: 'ing-gen-main', amount: 300 },
      { ingredientId: 'ing-gen-gohan', amount: 150 },
    ],
    cookingInstructions: '1. 各種有機料理はスペックで対応する。\n2. 小鉢・ごはん・デザートは、通常営業通り提供\n3. メイン料理はオーダー時作成\n4. セットを組み提供する',
    description: '有機料理をセットにしたオーガニックコース（有機52%、非有機48%）写真変更',
    managerApproved: '中村誠治',
    creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年1月25日',
    startDate: '令和7年2月1日',
    reviewDate: '令和7年8月25日',
    deadline: '一年間',
    courseTargetNum: '年間3600食',
    singleTargetNum: '',
    changeDetails: '写真変更',
    updatedAt: now,
  },

  // ---------- 3. 有機野菜サラダ（5版） ----------
  {
    id: 'menu-salad-0',
    name: '有機野菜サラダ 前年引継ぎ',
    masterName: '有機野菜サラダ',
    versionName: '前年引継ぎ',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-korinky', amount: 30 },
      { ingredientId: 'ing-org-piman', amount: 20 },
      { ingredientId: 'ing-org-mint', amount: 1 },
      { ingredientId: 'ing-org-ninjin', amount: 22.5 },
      { ingredientId: 'ing-org-shoyu', amount: 3 },
      { ingredientId: 'ing-org-kurozu', amount: 3.5 },
      { ingredientId: 'ing-org-olive', amount: 2.8 },
      { ingredientId: 'ing-org-sugar', amount: 2 },
    ],
    cookingInstructions: '1. 有機野菜をカット\n2. 人参・コリンキー塩もみする\n3. 皿に盛りつける\n4. ドレッシング調合\n5. サラダにかける\n6. 完成',
    description: '有機野菜100%のサラダ（コリンキー・ピーマン・ミント）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年8月25日', startDate: '令和6年9月1日',
    reviewDate: '令和6年10月25日', deadline: '令和6年10月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間60食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salad-1',
    name: '有機野菜サラダ №1',
    masterName: '有機野菜サラダ',
    versionName: '第1版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-karashina', amount: 30 },
      { ingredientId: 'ing-org-mizuna', amount: 20 },
      { ingredientId: 'ing-org-mint', amount: 1 },
      { ingredientId: 'ing-org-ninjin', amount: 22.5 },
      { ingredientId: 'ing-org-shoyu', amount: 3 },
      { ingredientId: 'ing-org-kurozu', amount: 3.5 },
      { ingredientId: 'ing-org-olive', amount: 2.8 },
      { ingredientId: 'ing-org-sugar', amount: 2 },
    ],
    cookingInstructions: '1. 有機野菜をカット\n2. 人参を塩もみする\n3. 皿に盛りつける\n4. ドレッシング調合\n5. サラダにかける\n6. 完成',
    description: '有機野菜100%のサラダ（カラシナ・水菜・ミント）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年10月25日', startDate: '令和6年11月1日',
    reviewDate: '令和6年12月25日', deadline: '令和6年12月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間60食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salad-2',
    name: '有機野菜サラダ №2',
    masterName: '有機野菜サラダ',
    versionName: '第2版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-cauliflwr', amount: 30 },
      { ingredientId: 'ing-org-hatsukadk', amount: 20 },
      { ingredientId: 'ing-org-nabana', amount: 5 },
      { ingredientId: 'ing-org-ninjin', amount: 22.5 },
      { ingredientId: 'ing-org-shoyu', amount: 3 },
      { ingredientId: 'ing-org-kurozu', amount: 3.5 },
      { ingredientId: 'ing-org-olive', amount: 2.8 },
      { ingredientId: 'ing-org-sugar', amount: 2 },
    ],
    cookingInstructions: '1. 有機野菜をカット\n2. 人参を塩もみする,カリフラワー・菜の花はボイル\n3. 皿に盛りつける\n4. ドレッシング調合\n5. サラダにかける\n6. 完成',
    description: '有機野菜100%のサラダ（カリフラワー・はつか大根・菜花）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年12月25日', startDate: '令和7年1月1日',
    reviewDate: '令和7年3月25日', deadline: '令和7年3月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間60食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salad-3',
    name: '有機野菜サラダ №3',
    masterName: '有機野菜サラダ',
    versionName: '第3版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-karashina', amount: 30 },
      { ingredientId: 'ing-org-tamanegi', amount: 20 },
      { ingredientId: 'ing-org-beets', amount: 5 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-org-ninjin', amount: 2.5 },
      { ingredientId: 'ing-org-shoyu', amount: 3 },
      { ingredientId: 'ing-org-kurozu', amount: 3.5 },
      { ingredientId: 'ing-org-olive', amount: 2.8 },
      { ingredientId: 'ing-org-sugar', amount: 2 },
    ],
    cookingInstructions: '1. 有機野菜をカット\n2. ビーツを塩もみする\n3. 皿に盛りつける\n4. ドレッシング調合\n5. サラダにかける\n6. 完成',
    description: '有機野菜100%のサラダ（カラシナ・たまねぎ・ビーツ・カブ）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年3月25日', startDate: '令和7年4月1日',
    reviewDate: '令和7年5月25日', deadline: '令和7年5月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間60食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salad-4',
    name: '有機野菜サラダ №4',
    masterName: '有機野菜サラダ',
    versionName: '第4版',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-zucchini', amount: 30 },
      { ingredientId: 'ing-org-tamanegi', amount: 20 },
      { ingredientId: 'ing-org-beets', amount: 5 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-org-mint', amount: 2 },
      { ingredientId: 'ing-org-ninjin', amount: 2.5 },
      { ingredientId: 'ing-org-shoyu', amount: 3 },
      { ingredientId: 'ing-org-kurozu', amount: 3.5 },
      { ingredientId: 'ing-org-olive', amount: 2.8 },
      { ingredientId: 'ing-org-sugar', amount: 2 },
    ],
    cookingInstructions: '1. 有機野菜をカット\n2. ビーツを塩もみする\n3. 皿に盛りつける\n4. ドレッシング調合\n5. サラダにかける\n6. 完成',
    description: '有機野菜100%のサラダ（ズッキーニ・たまねぎ・ビーツ・カブ・ミント）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年5月25日', startDate: '令和7年6月1日',
    reviewDate: '令和7年7月25日', deadline: '令和7年7月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間60食',
    changeDetails: '具材の変更', updatedAt: now,
  },

  // ---------- 4. 有機野菜のバーニャカウダ ----------
  {
    id: 'menu-bagna-4',
    name: '有機野菜のバーニャカウダ',
    masterName: '有機野菜のバーニャカウダ',
    versionName: '第4版',
    isActiveVersion: true,
    price: 650, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-kurozu', amount: 5 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-tonyu', amount: 50 },
      { ingredientId: 'ing-org-olive', amount: 20 },
      { ingredientId: 'ing-org-ninjin', amount: 30 },
      { ingredientId: 'ing-org-italianp', amount: 10 },
      { ingredientId: 'ing-org-tamanegi', amount: 20 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-gen-spice', amount: 0.2 },
    ],
    cookingInstructions: '1. 有機黒酢・グラニュー糖・有機豆乳・オリーブオイルを混ぜ合わせる\n2. 有機野菜をカット・ボイルする。\n3. 皿に盛り付け、ソースを添えて完成',
    description: '有機野菜のバーニャカウダ（有機99.9%）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年3月25日', startDate: '令和7年4月1日',
    reviewDate: '令和7年5月25日', deadline: '令和7年5月31日',
    courseTargetNum: '', singleTargetNum: '60食',
    changeDetails: '具材の変更', updatedAt: now,
  },

  // ---------- 5. 有機ピクルス ----------
  {
    id: 'menu-pickles-1',
    name: '有機ピクルス',
    masterName: '有機ピクルス',
    versionName: '第1版',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-ninjin', amount: 100 },
      { ingredientId: 'ing-org-rosemary', amount: 3 },
      { ingredientId: 'ing-org-sugar', amount: 40 },
      { ingredientId: 'ing-org-kurozu', amount: 200 },
    ],
    cookingInstructions: '1. 野菜を食べやすい大きさにカットし、塩をふる\n2. ピクルス液に漬け込み、冷蔵庫で2日ほど漬け込む\n3. 取り出し完成',
    description: '有機野菜のピクルス（有機100%）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年10月25日', startDate: '令和6年11月1日',
    reviewDate: '令和7年10月25日', deadline: '一年間',
    courseTargetNum: '', singleTargetNum: '50食',
    changeDetails: '割合変更/目標数変更', updatedAt: now,
  },

  // ---------- 6. ブルーベリー酢 ----------
  {
    id: 'menu-blueberry-1',
    name: 'ブルーベリー酢',
    masterName: 'ブルーベリー酢',
    versionName: '第1版',
    isActiveVersion: true,
    price: 250, category: 'ドリンク',
    recipe: [
      { ingredientId: 'ing-org-sugar', amount: 4 },
      { ingredientId: 'ing-org-kurozu', amount: 7 },
      { ingredientId: 'ing-gen-blueberry', amount: 0.5 },
    ],
    cookingInstructions: '1. オーガニック用ブルーベリー酢を水で割る\n2. 冷やして完成',
    description: '有機食前酢（有機96%）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年8月25日', startDate: '令和6年9月1日',
    reviewDate: '令和7年8月25日', deadline: '一年間',
    courseTargetNum: '3600食', singleTargetNum: '30食',
    changeDetails: 'なし', updatedAt: now,
  },

  // ---------- 7. 有機豆乳のポタージュ ----------
  {
    id: 'menu-potage-1',
    name: '有機豆乳のポタージュ',
    masterName: '有機豆乳のポタージュ',
    versionName: '第1版',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-kurozu', amount: 5 },
      { ingredientId: 'ing-org-sugar', amount: 10 },
      { ingredientId: 'ing-org-tonyu', amount: 150 },
      { ingredientId: 'ing-org-yasai', amount: 50 },
      { ingredientId: 'ing-org-parsley', amount: 2 },
    ],
    cookingInstructions: '1. 有機人参をスライスし、蒸す。\n2. 蒸した有機野菜をフードプロセッサーでペーストにする\n3. 鍋に豆乳・水・塩・砂糖・有機野菜を入れ80℃まで加熱\n4. 仕上げに黒酢を入れ完成\n5. 器に盛りつける',
    description: '有機豆乳のポタージュ（有機100%）パセリは冬場10月～4月は冷凍を使用',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年8月25日', startDate: '令和6年9月1日',
    reviewDate: '令和7年8月25日', deadline: '一年間',
    courseTargetNum: '', singleTargetNum: '80食',
    changeDetails: '目標数変更', updatedAt: now,
  },

  // ---------- 8. 有機野菜とサルサソース（6版） ----------
  {
    id: 'menu-salsa-0',
    name: '有機野菜とサルサソース 前年引継ぎ',
    masterName: '有機野菜とサルサソース',
    versionName: '前年引継ぎ',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-korinky', amount: 20 },
      { ingredientId: 'ing-org-ninjin', amount: 20 },
      { ingredientId: 'ing-org-kyuri', amount: 30 },
      { ingredientId: 'ing-org-passion', amount: 10 },
      { ingredientId: 'ing-org-kurozu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi-s', amount: 4 },
      { ingredientId: 'ing-org-shoyu', amount: 15 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-olive', amount: 10 },
      { ingredientId: 'ing-gen-petitdrip', amount: 1 },
      { ingredientId: 'ing-gen-bpepper', amount: 0.2 },
    ],
    cookingInstructions: '1. 玉ねぎを刻む ※サルサソース\n2. 有機醤油と有機黒酢を加える ※サルサソース\n3. 有機野菜を一口大に切る・ボイルする\n4. 一口大に切った有機野菜を器に盛り付ける\n5. サルサソースをかける\n6. 完成',
    description: '有機野菜とサルサソース（有機99.1%）コリンキー・キュウリ・パッションフルーツ',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年7月25日', startDate: '令和6年8月1日',
    reviewDate: '令和6年9月25日', deadline: '令和6年9月30日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間90食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salsa-1',
    name: '有機野菜とサルサソース №1',
    masterName: '有機野菜とサルサソース',
    versionName: '第1版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-piman', amount: 30 },
      { ingredientId: 'ing-org-ninjin', amount: 20 },
      { ingredientId: 'ing-org-nasu', amount: 20 },
      { ingredientId: 'ing-org-satoimo', amount: 10 },
      { ingredientId: 'ing-org-kurozu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi-s', amount: 4 },
      { ingredientId: 'ing-org-shoyu', amount: 15 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-olive', amount: 10 },
      { ingredientId: 'ing-gen-petitdrip', amount: 1 },
      { ingredientId: 'ing-gen-bpepper', amount: 0.2 },
    ],
    cookingInstructions: '1. 玉ねぎを刻む ※サルサソース\n2. 有機醤油と有機黒酢を加える ※サルサソース\n3. 有機野菜を一口大に切る・ボイルする\n4. 一口大に切った有機野菜を器に盛り付ける\n5. サルサソースをかける\n6. 完成',
    description: '有機野菜とサルサソース（有機99.1%）ピーマン・ナス・里芋',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年9月25日', startDate: '令和6年10月1日',
    reviewDate: '令和6年11月25日', deadline: '令和6年11月30日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間90食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salsa-2',
    name: '有機野菜とサルサソース №2',
    masterName: '有機野菜とサルサソース',
    versionName: '第2版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-hatsukadk', amount: 30 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-org-cauliflwr', amount: 20 },
      { ingredientId: 'ing-org-karashina', amount: 10 },
      { ingredientId: 'ing-org-ninjin', amount: 10 },
      { ingredientId: 'ing-org-kurozu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi-s', amount: 4 },
      { ingredientId: 'ing-org-shoyu', amount: 15 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-olive', amount: 10 },
      { ingredientId: 'ing-gen-petitdrip', amount: 1 },
      { ingredientId: 'ing-gen-bpepper', amount: 0.2 },
    ],
    cookingInstructions: '1. 玉ねぎを刻む ※サルサソース\n2. 有機醤油と有機黒酢を加える ※サルサソース\n3. 有機野菜を一口大に切る・ボイルする\n4. 一口大に切った有機野菜を器に盛り付ける\n5. サルサソースをかける\n6. 完成',
    description: '有機野菜とサルサソース（有機99.2%）はつか大根・カブ・カリフラワー・カラシナ',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年11月25日', startDate: '令和6年12月1日',
    reviewDate: '令和7年1月25日', deadline: '令和7年1月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間90食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salsa-3',
    name: '有機野菜とサルサソース №3',
    masterName: '有機野菜とサルサソース',
    versionName: '第3版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-ninjin', amount: 30 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-org-cauliflwr', amount: 20 },
      { ingredientId: 'ing-org-nabana', amount: 10 },
      { ingredientId: 'ing-org-kurozu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi-s', amount: 4 },
      { ingredientId: 'ing-org-shoyu', amount: 15 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-olive', amount: 10 },
      { ingredientId: 'ing-gen-petitdrip', amount: 1 },
      { ingredientId: 'ing-gen-bpepper', amount: 0.2 },
    ],
    cookingInstructions: '1. 玉ねぎを刻む ※サルサソース\n2. 有機醤油と有機黒酢を加える ※サルサソース\n3. 有機野菜を一口大に切る・ボイルする\n4. 一口大に切った有機野菜を器に盛り付ける\n5. サルサソースをかける\n6. 完成',
    description: '有機野菜とサルサソース（有機99.1%）人参・カブ・カリフラワー・菜花',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年1月25日', startDate: '令和7年2月1日',
    reviewDate: '令和7年3月25日', deadline: '令和7年3月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間90食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salsa-4',
    name: '有機野菜とサルサソース №4',
    masterName: '有機野菜とサルサソース',
    versionName: '第4版',
    isActiveVersion: false,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-ninjin', amount: 30 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi', amount: 20 },
      { ingredientId: 'ing-org-italianp', amount: 10 },
      { ingredientId: 'ing-org-kurozu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi-s', amount: 4 },
      { ingredientId: 'ing-org-shoyu', amount: 15 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-olive', amount: 10 },
      { ingredientId: 'ing-gen-petitdrip', amount: 1 },
      { ingredientId: 'ing-gen-bpepper', amount: 0.2 },
    ],
    cookingInstructions: '1. 玉ねぎを刻む ※サルサソース\n2. 有機醤油と有機黒酢を加える ※サルサソース\n3. 有機野菜を一口大に切る・ボイルする\n4. 一口大に切った有機野菜を器に盛り付ける\n5. サルサソースをかける\n6. 完成',
    description: '有機野菜とサルサソース（有機99.1%）人参・カブ・たまねぎ・イタリアンパセリ',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年3月25日', startDate: '令和7年4月1日',
    reviewDate: '令和7年5月25日', deadline: '令和7年5月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間90食',
    changeDetails: '具材の変更', updatedAt: now,
  },
  {
    id: 'menu-salsa-5',
    name: '有機野菜とサルサソース №5',
    masterName: '有機野菜とサルサソース',
    versionName: '第5版',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-jagaimo', amount: 30 },
      { ingredientId: 'ing-org-kabu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi', amount: 20 },
      { ingredientId: 'ing-org-zucchini', amount: 10 },
      { ingredientId: 'ing-org-kurozu', amount: 20 },
      { ingredientId: 'ing-org-tamanegi-s', amount: 4 },
      { ingredientId: 'ing-org-shoyu', amount: 15 },
      { ingredientId: 'ing-org-sugar', amount: 5 },
      { ingredientId: 'ing-org-olive', amount: 10 },
      { ingredientId: 'ing-gen-petitdrip', amount: 1 },
      { ingredientId: 'ing-gen-bpepper', amount: 0.2 },
    ],
    cookingInstructions: '1. 玉ねぎを刻む ※サルサソース\n2. 有機醤油と有機黒酢を加える ※サルサソース\n3. 有機野菜を一口大に切る・ボイルする\n4. 一口大に切った有機野菜を器に盛り付ける\n5. サルサソースをかける\n6. 完成',
    description: '有機野菜とサルサソース（有機99.1%）ジャガイモ・カブ・たまねぎ・ズッキーニ',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年5月25日', startDate: '令和7年6月1日',
    reviewDate: '令和7年7月25日', deadline: '令和7年7月31日',
    courseTargetNum: '年間3600食', singleTargetNum: '年間90食',
    changeDetails: '具材の変更', updatedAt: now,
  },

  // ---------- 9. 黒酢添加料理（4コース） ----------
  {
    id: 'menu-kurozu-abc',
    name: '黒酢添加料理（ABC）',
    masterName: '黒酢添加料理',
    versionName: '黒酢ランチABC',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-kurozu', amount: 1 },
      { ingredientId: 'ing-gen-sonota', amount: 99 },
    ],
    cookingInstructions: '黒酢ランチコース（ABC）の内容です。\nA 黒酢カレー\nB 月替わり麺\nC 月替わり魚\n黒酢の郷桷志田では、すべての料理に有機黒酢を使用しております。',
    description: '黒酢ランチコースABC（有機1%）A黒酢カレー B月替わり麺 C月替わり魚',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年9月25日', startDate: '令和6年10月1日',
    reviewDate: '令和7年9月25日', deadline: '一年間',
    changeDetails: '各コースに分類', updatedAt: now,
  },
  {
    id: 'menu-kurozu-defg',
    name: '黒酢添加料理（DEFG）',
    masterName: '黒酢添加料理',
    versionName: '黒酢ランチDEFG',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-kurozu', amount: 1 },
      { ingredientId: 'ing-gen-sonota', amount: 99 },
    ],
    cookingInstructions: '黒酢ランチコース（DEFG）の内容です。\nD 月替わりパスタ\nE 黒酢酢豚\nF エビチリ\nG 黒豚ロースステーキ\n黒酢の郷桷志田では、すべての料理に有機黒酢を使用しております。',
    description: '黒酢ランチコースDEFG（有機1%）Dパスタ E黒酢酢豚 Fエビチリ Gステーキ',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年9月25日', startDate: '令和6年10月1日',
    reviewDate: '令和7年9月25日', deadline: '一年間',
    changeDetails: '各コースに分類', updatedAt: now,
  },
  {
    id: 'menu-kurozu-steak',
    name: '黒酢添加料理（ステーキ）',
    masterName: '黒酢添加料理',
    versionName: '黒酢もろみステーキ',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-kurozu', amount: 1 },
      { ingredientId: 'ing-gen-sonota', amount: 99 },
    ],
    cookingInstructions: '黒酢もろみ黒毛和牛のステーキコース（もも・サーロイン）の内容です。\n黒酢の郷桷志田では、すべての料理に有機黒酢を使用しております。',
    description: '黒酢もろみ黒毛和牛のステーキコース（有機1%）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年9月25日', startDate: '令和6年10月1日',
    reviewDate: '令和7年9月25日', deadline: '一年間',
    changeDetails: '各コースに分類', updatedAt: now,
  },
  {
    id: 'menu-kurozu-maguro',
    name: '黒酢添加料理（まぐろ）',
    masterName: '黒酢添加料理',
    versionName: '市場直送まぐろ',
    isActiveVersion: true,
    price: 0, category: '料理',
    recipe: [
      { ingredientId: 'ing-org-kurozu', amount: 1 },
      { ingredientId: 'ing-gen-sonota', amount: 99 },
    ],
    cookingInstructions: '市場直送 まぐろづくしコースの内容です。\n黒酢の郷桷志田では、すべての料理に有機黒酢を使用しております。',
    description: '市場直送まぐろづくしコース（有機1%）',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和7年5月25日', startDate: '令和7年6月1日',
    reviewDate: '令和7年8月25日', deadline: '3か月',
    changeDetails: '各コースに分類', updatedAt: now,
  },

  // ---------- 10. 有機コーヒー ----------
  {
    id: 'menu-coffee-0',
    name: '有機コーヒー 前年引継ぎ',
    masterName: '有機コーヒー',
    versionName: '前年引継ぎ',
    isActiveVersion: false,
    price: 0, category: 'ドリンク',
    recipe: [
      { ingredientId: 'ing-org-coffee', amount: 7 },
    ],
    cookingInstructions: '1. 豆をミルで挽く\n2. コーヒーメーカーで抽出する\n3. カップに注ぐ\n4. 完成',
    description: '有機コーヒー（有機100%）トーホー有機コーヒー',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和5年12月25日', startDate: '令和6年1月1日',
    reviewDate: '令和6年8月25日', deadline: '一年間',
    courseTargetNum: '年間コース3600食', singleTargetNum: '年間単品120食',
    changeDetails: '目標数の変更', updatedAt: now,
  },
  {
    id: 'menu-coffee-1',
    name: '有機コーヒー',
    masterName: '有機コーヒー',
    versionName: '現行版',
    isActiveVersion: true,
    price: 0, category: 'ドリンク',
    recipe: [
      { ingredientId: 'ing-org-coffee', amount: 7 },
    ],
    cookingInstructions: '1. 豆をミルで挽く\n2. コーヒーメーカーで抽出する\n3. カップに注ぐ\n4. 完成',
    description: '有機コーヒー（有機100%）トーホー有機コーヒー',
    managerApproved: '中村誠治', creatorApproved: '田中大輔',
    targetCreatedDate: '令和6年8月25日', startDate: '令和6年9月1日',
    reviewDate: '令和7年8月25日', deadline: '一年間',
    courseTargetNum: '年間コース3600食', singleTargetNum: '年間単品120食',
    changeDetails: '特になし', updatedAt: now,
  },
];


// ============================================================================
// Firestore へ書き込み
// ============================================================================
async function restore() {
  console.log(`=== 復元開始 ===`);
  console.log(`原材料: ${ingredients.length}件`);
  console.log(`メニュー: ${menus.length}件`);

  // 1. 原材料マスタ
  console.log('\n--- 原材料マスタを書き込み中... ---');
  await setDoc(doc(db, 'restaurants', 'ingredients'), { data: ingredients });
  console.log('✅ 原材料マスタ完了');

  // 2. メニュー
  console.log('\n--- メニューを書き込み中... ---');
  await setDoc(doc(db, 'restaurants', 'menus'), { data: menus });
  console.log('✅ メニュー完了');

  console.log('\n=== 復元完了 ===');
  process.exit(0);
}

restore().catch(e => {
  console.error('復元エラー:', e);
  process.exit(1);
});
